-- Migration 008: Transition from Food & Beverages to Auto Parts
-- This migration deletes all Food & Beverage products and adds Auto Parts products

-- Step 1: Delete all Food & Beverage products
DELETE FROM products 
WHERE category_id IN (
    SELECT id FROM categories 
    WHERE name = 'Food & Beverages' OR slug = 'food-beverages'
);

-- Step 2: Delete Food & Beverages category
DELETE FROM categories 
WHERE name = 'Food & Beverages' OR slug = 'food-beverages';

-- Step 3: Create Auto Parts category
INSERT INTO categories (name, slug, description, sort_order, is_active) 
VALUES ('Auto Parts', 'auto-parts', 'Quality auto parts for every vehicle. Find the perfect parts for your car.', 5, TRUE)
ON CONFLICT (slug) DO UPDATE SET 
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    sort_order = EXCLUDED.sort_order,
    is_active = EXCLUDED.is_active,
    updated_at = NOW();

-- Step 4: Add Auto Parts products
INSERT INTO products (name, slug, description, short_description, sku, price, compare_price, category_id, inventory_quantity, track_inventory, allow_backorder, status, featured, images) 
SELECT 
    unnest(ARRAY[
        'Brake Pads',
        'Oil Filter',
        'Spark Plugs',
        'Air Filter',
        'Car Battery',
        'Alternator',
        'Starter Motor',
        'Fuel Pump',
        'Water Pump',
        'Timing Belt',
        'Radiator',
        'Shock Absorbers',
        'Struts',
        'Ball Joints',
        'Tie Rod Ends',
        'CV Axle',
        'Wheel Bearing',
        'Brake Rotors',
        'Brake Calipers',
        'Clutch Kit',
        'Headlights',
        'Taillights',
        'Side Mirrors',
        'Wiper Blades',
        'Engine Oil',
        'Transmission Fluid',
        'Coolant',
        'Brake Fluid',
        'Power Steering Fluid',
        'Serpentine Belt',
        'Fan Belt',
        'Thermostat',
        'Oxygen Sensor',
        'Mass Air Flow Sensor',
        'Fuel Injector',
        'Ignition Coil',
        'Distributor Cap',
        'Rotor',
        'Spark Plug Wires',
        'Fuel Filter',
        'PCV Valve',
        'EGR Valve',
        'Thermostat Housing',
        'Water Hose',
        'Radiator Hose',
        'Heater Hose',
        'Brake Lines',
        'Fuel Lines',
        'Exhaust Manifold',
        'Muffler',
        'Catalytic Converter',
        'Exhaust Pipe'
    ]) as name,
    unnest(ARRAY[
        'brake-pads',
        'oil-filter',
        'spark-plugs',
        'air-filter',
        'car-battery',
        'alternator',
        'starter-motor',
        'fuel-pump',
        'water-pump',
        'timing-belt',
        'radiator',
        'shock-absorbers',
        'struts',
        'ball-joints',
        'tie-rod-ends',
        'cv-axle',
        'wheel-bearing',
        'brake-rotors',
        'brake-calipers',
        'clutch-kit',
        'headlights',
        'taillights',
        'side-mirrors',
        'wiper-blades',
        'engine-oil',
        'transmission-fluid',
        'coolant',
        'brake-fluid',
        'power-steering-fluid',
        'serpentine-belt',
        'fan-belt',
        'thermostat',
        'oxygen-sensor',
        'mass-air-flow-sensor',
        'fuel-injector',
        'ignition-coil',
        'distributor-cap',
        'rotor',
        'spark-plug-wires',
        'fuel-filter',
        'pcv-valve',
        'egr-valve',
        'thermostat-housing',
        'water-hose',
        'radiator-hose',
        'heater-hose',
        'brake-lines',
        'fuel-lines',
        'exhaust-manifold',
        'muffler',
        'catalytic-converter',
        'exhaust-pipe'
    ]) as slug,
    unnest(ARRAY[
        'High-quality brake pads for reliable stopping power. Fits most vehicle models.',
        'Premium oil filter for optimal engine performance and longevity.',
        'Durable spark plugs for improved fuel efficiency and engine performance.',
        'High-efficiency air filter for better engine airflow and performance.',
        'Long-lasting car battery with reliable cold-cranking performance.',
        'Remanufactured alternator for consistent electrical power generation.',
        'Heavy-duty starter motor for reliable engine ignition.',
        'Precision fuel pump for consistent fuel delivery to the engine.',
        'Durable water pump for efficient engine cooling system operation.',
        'High-quality timing belt for precise engine timing and reliability.',
        'Efficient radiator for optimal engine heat dissipation.',
        'Premium shock absorbers for smooth ride and vehicle stability.',
        'Heavy-duty struts for improved suspension performance.',
        'Durable ball joints for precise steering and suspension control.',
        'Quality tie rod ends for responsive steering control.',
        'Reliable CV axle for smooth power transfer to wheels.',
        'Precision wheel bearing for smooth wheel rotation.',
        'High-performance brake rotors for consistent braking performance.',
        'Quality brake calipers for reliable brake pad engagement.',
        'Complete clutch kit for smooth gear shifting.',
        'Bright LED headlights for improved nighttime visibility.',
        'Energy-efficient LED taillights for better road safety.',
        'Adjustable side mirrors for enhanced visibility.',
        'Premium wiper blades for clear windshield in all weather.',
        'Synthetic engine oil for superior engine protection.',
        'High-quality transmission fluid for smooth gear shifts.',
        'Long-life coolant for effective engine temperature control.',
        'Dot 4 brake fluid for reliable braking performance.',
        'Premium power steering fluid for smooth steering operation.',
        'Durable serpentine belt for reliable accessory drive.',
        'Heavy-duty fan belt for efficient cooling system operation.',
        'Precision thermostat for optimal engine temperature regulation.',
        'Accurate oxygen sensor for efficient fuel management.',
        'Quality mass air flow sensor for optimal engine performance.',
        'Precision fuel injector for accurate fuel delivery.',
        'High-performance ignition coil for reliable spark generation.',
        'Quality distributor cap for consistent ignition timing.',
        'Durable rotor for reliable ignition system operation.',
        'Premium spark plug wires for efficient spark transfer.',
        'High-efficiency fuel filter for clean fuel delivery.',
        'Quality PCV valve for proper crankcase ventilation.',
        'Reliable EGR valve for reduced emissions.',
        'Durable thermostat housing for leak-free cooling system.',
        'Flexible water hose for reliable coolant circulation.',
        'Heavy-duty radiator hose for efficient cooling system.',
        'Quality heater hose for effective cabin heating.',
        'Steel brake lines for reliable brake fluid transfer.',
        'Durable fuel lines for consistent fuel delivery.',
        'Performance exhaust manifold for improved engine efficiency.',
        'Quality muffler for reduced exhaust noise.',
        'High-efficiency catalytic converter for emission control.',
        'Stainless steel exhaust pipe for durability.'
    ]) as description,
    unnest(ARRAY[
        'Brake Pads - High Quality',
        'Oil Filter - Premium',
        'Spark Plugs - Durable',
        'Air Filter - High Efficiency',
        'Car Battery - Long Lasting',
        'Alternator - Remanufactured',
        'Starter Motor - Heavy Duty',
        'Fuel Pump - Precision',
        'Water Pump - Durable',
        'Timing Belt - High Quality',
        'Radiator - Efficient',
        'Shock Absorbers - Premium',
        'Struts - Heavy Duty',
        'Ball Joints - Durable',
        'Tie Rod Ends - Quality',
        'CV Axle - Reliable',
        'Wheel Bearing - Precision',
        'Brake Rotors - High Performance',
        'Brake Calipers - Quality',
        'Clutch Kit - Complete',
        'Headlights - LED',
        'Taillights - Energy Efficient',
        'Side Mirrors - Adjustable',
        'Wiper Blades - Premium',
        'Engine Oil - Synthetic',
        'Transmission Fluid - High Quality',
        'Coolant - Long Life',
        'Brake Fluid - Dot 4',
        'Power Steering Fluid - Premium',
        'Serpentine Belt - Durable',
        'Fan Belt - Heavy Duty',
        'Thermostat - Precision',
        'Oxygen Sensor - Accurate',
        'Mass Air Flow Sensor - Quality',
        'Fuel Injector - Precision',
        'Ignition Coil - High Performance',
        'Distributor Cap - Quality',
        'Rotor - Durable',
        'Spark Plug Wires - Premium',
        'Fuel Filter - High Efficiency',
        'PCV Valve - Quality',
        'EGR Valve - Reliable',
        'Thermostat Housing - Durable',
        'Water Hose - Flexible',
        'Radiator Hose - Heavy Duty',
        'Heater Hose - Quality',
        'Brake Lines - Steel',
        'Fuel Lines - Durable',
        'Exhaust Manifold - Performance',
        'Muffler - Quality',
        'Catalytic Converter - High Efficiency',
        'Exhaust Pipe - Stainless Steel'
    ]) as short_description,
    unnest(ARRAY[
        'AP-001', 'AP-002', 'AP-003', 'AP-004', 'AP-005',
        'AP-006', 'AP-007', 'AP-008', 'AP-009', 'AP-010',
        'AP-011', 'AP-012', 'AP-013', 'AP-014', 'AP-015',
        'AP-016', 'AP-017', 'AP-018', 'AP-019', 'AP-020',
        'AP-021', 'AP-022', 'AP-023', 'AP-024', 'AP-025',
        'AP-026', 'AP-027', 'AP-028', 'AP-029', 'AP-030',
        'AP-031', 'AP-032', 'AP-033', 'AP-034', 'AP-035',
        'AP-036', 'AP-037', 'AP-038', 'AP-039', 'AP-040',
        'AP-041', 'AP-042', 'AP-043', 'AP-044', 'AP-045',
        'AP-046', 'AP-047', 'AP-048', 'AP-049', 'AP-050',
        'AP-051', 'AP-052', 'AP-053', 'AP-054', 'AP-055'
    ]) as sku,
    unnest(ARRAY[
        45.99, 15.99, 25.99, 18.99, 89.99,
        199.99, 149.99, 129.99, 79.99, 35.99,
        149.99, 69.99, 89.99, 45.99, 35.99,
        79.99, 55.99, 59.99, 89.99, 199.99,
        79.99, 59.99, 35.99, 19.99, 29.99,
        39.99, 24.99, 19.99, 14.99, 16.99,
        29.99, 24.99, 45.99, 89.99, 65.99,
        35.99, 29.99, 19.99, 45.99, 25.99,
        39.99, 29.99, 24.99, 19.99, 35.99,
        45.99, 39.99, 129.99, 59.99, 49.99
    ]) as price,
    unnest(ARRAY[
        NULL, NULL, NULL, NULL, NULL,
        NULL, NULL, NULL, NULL, NULL,
        NULL, NULL, NULL, NULL, NULL,
        NULL, NULL, NULL, NULL, NULL,
        NULL, NULL, NULL, NULL, NULL,
        NULL, NULL, NULL, NULL, NULL,
        NULL, NULL, NULL, NULL, NULL,
        NULL, NULL, NULL, NULL, NULL,
        NULL, NULL, NULL, NULL, NULL,
        NULL, NULL, NULL, NULL, NULL
    ]) as compare_price,
    (SELECT id FROM categories WHERE slug = 'auto-parts') as category_id,
    100 as inventory_quantity,
    TRUE as track_inventory,
    TRUE as allow_backorder,
    'active' as status,
    FALSE as featured,
    unnest(ARRAY[
        '["auto-parts/brake-pads.jpg"]',
        '["auto-parts/oil-filter.jpg"]',
        '["auto-parts/spark-plugs.jpg"]',
        '["auto-parts/air-filter.jpg"]',
        '["auto-parts/battery.jpg"]',
        '["auto-parts/alternator.jpg"]',
        '["auto-parts/starter-motor.jpg"]',
        '["auto-parts/fuel-pump.jpg"]',
        '["auto-parts/water-pump.jpg"]',
        '["auto-parts/timing-belt.jpg"]',
        '["auto-parts/radiator.jpg"]',
        '["auto-parts/shock-absorbers.jpg"]',
        '["auto-parts/struts.jpg"]',
        '["auto-parts/ball-joints.jpg"]',
        '["auto-parts/tie-rod-ends.jpg"]',
        '["auto-parts/cv-axle.jpg"]',
        '["auto-parts/wheel-bearing.jpg"]',
        '["auto-parts/brake-rotors.jpg"]',
        '["auto-parts/brake-calipers.jpg"]',
        '["auto-parts/clutch-kit.jpg"]',
        '["auto-parts/headlights.jpg"]',
        '["auto-parts/taillights.jpg"]',
        '["auto-parts/side-mirrors.jpg"]',
        '["auto-parts/wiper-blades.jpg"]',
        '["auto-parts/car-battery.jpg"]',
        '["auto-parts/engine-oil.jpg"]',
        '["auto-parts/transmission-fluid.jpg"]',
        '["auto-parts/coolant.jpg"]',
        '["auto-parts/brake-fluid.jpg"]',
        '["auto-parts/power-steering-fluid.jpg"]',
        '["auto-parts/serpentine-belt.jpg"]',
        '["auto-parts/fan-belt.jpg"]',
        '["auto-parts/thermostat.jpg"]',
        '["auto-parts/oxygen-sensor.jpg"]',
        '["auto-parts/mass-air-flow-sensor.jpg"]',
        '["auto-parts/fuel-injector.jpg"]',
        '["auto-parts/ignition-coil.jpg"]',
        '["auto-parts/distributor-cap.jpg"]',
        '["auto-parts/rotor.jpg"]',
        '["auto-parts/spark-plug-wires.jpg"]',
        '["auto-parts/fuel-filter.jpg"]',
        '["auto-parts/pcv-valve.jpg"]',
        '["auto-parts/egr-valve.jpg"]',
        '["auto-parts/thermostat-housing.jpg"]',
        '["auto-parts/water-hose.jpg"]',
        '["auto-parts/radiator-hose.jpg"]',
        '["auto-parts/heater-hose.jpg"]',
        '["auto-parts/brake-lines.jpg"]',
        '["auto-parts/fuel-lines.jpg"]',
        '["auto-parts/exhaust-manifold.jpg"]',
        '["auto-parts/muffler.jpg"]',
        '["auto-parts/catalytic-converter.jpg"]',
        '["auto-parts/exhaust-pipe.jpg"]'
    ])::jsonb as images
ON CONFLICT (sku) DO NOTHING;
